<?php

declare(strict_types=1);

namespace Tests\Domain;

use PHPUnit\Framework\TestCase;
use App\Domain\Transaction;
use InvalidArgumentException;

class TransactionTest extends TestCase
{
    public function testCreateDepositTransaction(): void
    {
        $amount = 50.0;
        $description = 'Allocation hebdomadaire';

        $transaction = new Transaction(Transaction::TYPE_DEPOSIT, $amount, $description);

        $this->assertEquals(Transaction::TYPE_DEPOSIT, $transaction->getType());
        $this->assertEquals($amount, $transaction->getAmount());
        $this->assertEquals($description, $transaction->getDescription());
        $this->assertInstanceOf(\DateTimeImmutable::class, $transaction->getDate());
    }

    public function testCreateExpenseTransaction(): void
    {
        $amount = 25.0;
        $description = 'Achat de livres';

        $transaction = new Transaction(Transaction::TYPE_EXPENSE, $amount, $description);

        $this->assertEquals(Transaction::TYPE_EXPENSE, $transaction->getType());
        $this->assertEquals($amount, $transaction->getAmount());
        $this->assertEquals($description, $transaction->getDescription());
    }

    public function testCreateAllowanceTransaction(): void
    {
        $amount = 20.0;
        $description = 'Allocation hebdomadaire automatique';

        $transaction = new Transaction(Transaction::TYPE_ALLOWANCE, $amount, $description);

        $this->assertEquals(Transaction::TYPE_ALLOWANCE, $transaction->getType());
        $this->assertEquals($amount, $transaction->getAmount());
        $this->assertEquals($description, $transaction->getDescription());
    }

    public function testCreateTransactionWithInvalidTypeThrowsException(): void
    {
        $invalidType = 'invalid_type';
        $amount = 50.0;
        $description = 'Test';

        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('Type de transaction invalide');

        new Transaction($invalidType, $amount, $description);
    }

    public function testCreateTransactionWithNegativeAmountThrowsException(): void
    {
        $type = Transaction::TYPE_DEPOSIT;
        $amount = -10.0;
        $description = 'Test';

        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('Le montant doit être positif');

        new Transaction($type, $amount, $description);
    }

    public function testCreateTransactionWithZeroAmountThrowsException(): void
    {
        $type = Transaction::TYPE_DEPOSIT;
        $amount = 0.0;
        $description = 'Test';

        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('Le montant doit être positif');

        new Transaction($type, $amount, $description);
    }

    public function testTransactionDateIsAutoGenerated(): void
    {
        $beforeCreation = new \DateTimeImmutable();

        $transaction = new Transaction(Transaction::TYPE_DEPOSIT, 50.0, 'Test');
        $transactionDate = $transaction->getDate();

        $afterCreation = new \DateTimeImmutable();
        $this->assertGreaterThanOrEqual($beforeCreation, $transactionDate);
        $this->assertLessThanOrEqual($afterCreation, $transactionDate);
    }
}

